### ISSUE TITLE
Provide azure blob storage access key via environment variable

### ISSUE THREAD

**Issue by alanjcastonguay** [stevearc/pypicloud#270]
I am running pypicloud on k8s and backed by Azure blob storage. I want to keep `storage.storage_account_key` (and other secret material) out of the giant config file. There's some prior art for reading from environment variables:

* `AWS_SECRET_ACCESS_KEY` read by boto3
* `GOOGLE_APPLICATION_CREDENTIALS` read by `pypicloud/storage/gcs.py`
* `PPC_AUTH_SIGNING_KEY ` for `auth.signing_key`

https://docs.microsoft.com/en-us/azure/storage/blobs/authorize-data-operations-cli#set-environment-variables-for-authorization-parameters suggests supporting well-known names `AZURE_STORAGE_ACCOUNT`, `AZURE_STORAGE_KEY`, etc.

This could be an adjustment similar to commit f9ca8312fdbf3c794030395646e45991b4f4e25a, or a more general extension of the settings-reader.

https://github.com/stevearc/pypicloud/blob/70f65f398fc9aac07658c42fa8794f95cc2b74eb/pypicloud/storage/azure_blob.py#L63-L75

**Comment by stevearc** [comment]
Added `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_KEY`. Not exactly sure how the others map to the existing arguments. Happy to add others if it makes sense, or feel free to put up a PR that does it

**Comment by alanjcastonguay** [comment]
The others don't really map to existing arguments. Commit f5c566ce1d670a306ec7c6600fba1d8200292614 is a reasonable & minimally-invasive change to me.

**Comment by KerberosMorphy** [comment]
Not sure if my issues is directly link to this one or not, but I'll ask here before creating a new one.
I'm currently look to create a server using `docker-compose` and I was hoping I could setup the config in the `docker-compose` via the `environment` key instead of a `config.ini` file:

```yaml
services:
  pypicloud:
    image: stevearc/pypicloud
    environment:
      PYPI_FALLBACK: cache
      ...
```

To do that it would be need to use as default value something like `os.environ.get("PYPI_FALLBACK", "redirect")`, but I didn't really look further for a cleaner way to do it.

With env variables it could also allowed `env_file`:

`docker-compose.yml`
```yaml
services:
  pypicloud:
    image: stevearc/pypicloud
    env_file:
      - .env
    environment:
      PYPI_DOWNLOAD_URL: https://${STAGE}.pypi.example.com
      ...
```

`.env`
```env
STAGE=prod
SESSION_VALIDATE_KEY=replaceme
```

`.env.staging`
```env
STAGE=staging
```

```shell
$ docker-compose --env-file ./.env.staging up
```
