### ISSUE TITLE
Use GAE's HTTPS support

### ISSUE THREAD

**Issue by yutongs-dmai** [stevearc/pypicloud#273]
I deployed the server on GAE. 

Used `ppc-make-config -t server.ini` to generate the .ini.

The app.yaml
```
runtime: python38
service: test

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "./creds.json"

entrypoint: pserve server.ini PORT=$PORT DB_PATH=/tmp

handlers:
- url: /static
  static_dir: static

- url: /*
  script: auto
```
I was able to download and upload the packages through command line. But when I try to use the Web UI, it gave me this error:
```
(index):8 Mixed Content: The page at 'https://test-dot-dmai-pypi-server.wl.r.appspot.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://test-dot-dmai-pypi-server.wl.r.appspot.com/static/1.1.7/css/lib/bootstrap-3.0.3.min.css'. This request has been blocked; the content must be served over HTTPS.
```

GAE supports https by default with its built-in SSL certificates. I wonder how I can enforce the https on the server side without introducing a new set of SSL certificates.

I tried the uWSGI server locally and it seems to work, but it asks for a custom SSL certificates.
