### ISSUE TITLE
Compose `sh: 1: /wait-for: not found`

### ISSUE THREAD

**Issue by KerberosMorphy** [stevearc/pypicloud#289]
For an unknow reason, if I clone this repo, and execute the following command without any change:

```sh
> cd /compose
> docker-compose -f mysql.yml up
```

I got the following error:

```sh
pypicloud_1  | sh: 1: /wait-for: not found
pypicloud_1 exited with code 127
```

I've try a lot of things to make it works, I end up using `restart: on-failure` to skip the `wait-for`.

Here my final setup:

```yaml
services:
  pypicloud:
    command: uwsgi --die-on-term /etc/pypicloud/config.ini
    restart: on-failure
    depends_on:
      - mysql
    image: stevearc/pypicloud:1.3.1
    ports:
      - "8080:8080"
    env_file:
      - base_config.env
      - file_storage_config.env
      - sql_cache_config.env
      - sql_auth_config.env
      - beaker_config.env
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: pypi
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
```

Did someone know why the `wait-for` isn't working and how to make it works?

The weirdest part is while using:

```yaml
services:
  pypicloud:
    command: ls -lah /wait-for
```

It did found it:

```sh
compose-pypicloud-1  | -rwxrwxrwx 1 root root 2.8K Oct 13 14:42 /wait-for
```
